kind: pipeline
type: docker
name: integration

steps:
  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    environment:
      SONARSECRET:
        from_secret: SonarQubeSecret
    commands:
      - exit 0
      - dotnet sonarscanner begin
        /k:"easv-devops_KLT_currency_AY7HNVWNEVvRW2O60Elc"
        /d:sonar.host.url="http://sonar.setgo.dk:9000"
        /d:sonar.token="$SONARSECRET"
      - dotnet build
      - dotnet sonarscanner end /d:sonar.token="$SONARSECRET"
