services:
  weather-frontend:
    image: hoeeg79/currency-converter-exercise-frontend:prod
  
  weather-api:
    image: hoeeg79/currency-converter-exercise-api:prod
  
  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - 8085:8085
    labels:
      - "com.centurylinklabs.watchtower.enable=false"