version: "3.3"

services:
  app-database:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432

  flyway:
    image: flyway/flyway:10
    command: migrate
    volumes:
      - ./DBMigrations:/flyway/sql
      - ./DBMigrations:/flyway/conf
    depends_on:
      - app-database
        
  frontend:
    build:
      context: Frontend
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    