version: "3.3"

services:
  app-database:
    image: postgres
    restart: always
    shm_size: 128mb
    hostname: app-database
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432

  flyway:
    image: flyway/flyway:10
    command: migrate
    volumes:
      - ./DBMigrations:/flyway/sql
      - ./DBMigrations:/flyway/conf
    depends_on:
      - app-database
        
  frontend:
    build:
      context: Frontend
      dockerfile: ./Dockerfile
    ports:
      - 8081:80
    depends_on: 
      - api
  
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - PGPASSWORD=secret
    ports:
      - 5100:8080
    hostname: api
    depends_on: 
      - app-database
        
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
      - WATCHTOWER_LABEL_ENABLE=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8080:8080